# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a86bbce459da95e983f43f8a6982a31e"
application_url = "https://ir-randy-greece-inside.trycloudflare.com"
embedded = true
name = "launch pad app"
handle = "launch-pad-app"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ir-randy-greece-inside.trycloudflare.com/auth/callback",
  "https://ir-randy-greece-inside.trycloudflare.com/auth/shopify/callback",
  "https://ir-randy-greece-inside.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
